name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set up database and run migrations
      - name: Set up database
        run: |
          python -m flask db init
          python -m flask db migrate
          python -m flask db upgrade

      # Run tests with pytest and coverage
      - name: Run tests
        run: |
          pytest --cov=app --cov-report=term-missing -v

      # Upload coverage reports (for GitHub Actions only)
      - name: Upload coverage report
        if: success()
        uses: codecov/codecov-action@v2
        with:
          files: "coverage.xml"

      