name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List Installed Dependencies
        run: pip freeze
       
      - name: Run Database Migrations
        run: |
          python -m flask db upgrade
          
      - name: Run tests
        env:
          AFRICASTALKING_API_KEY: ${{ secrets.AFRICASTALKING_API_KEY }}
          AFRICASTALKING_USERNAME: sandbox
        run: pytest -vv --cov=app tests/
